version: '3.9'
services:
  #app service
  job_api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # - MONGO_USER=${MONGO_USER}
      # - MONGO_PASSWORD=${MONGO_PASSWORD=}
    env_file:
      - ./.env
    depends_on:
      - mongo

  #nginx service
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  #Mongo service    
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
